# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 100, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 220, 231, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(290, 320, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.submitButton.clicked.connect(self.data_sent_to_database)

        # connect with database
        self.conn = pyodbc.connect('Driver={SQL Server};'
                                   'Server=DESKTOP-ONT87JO\SQLEXPRESS;'
                                   'Database=school;'
                                   'Trusted_Connection=yes;')

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 260, 231, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 180, 231, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 490, 231, 51))
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(164, 182, 232, 0), stop:0.55 rgba(250, 104, 255, 0), stop:0.98 rgba(124, 205, 236, 0), stop:1 rgba(0, 0, 0, 0));")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Pics/liquid-gradient-shape-fluid-abstract-color-background-holographic-organic-3d-design-neon-futuristic-element-blend-bubble-png.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(-70, -10, 231, 51))
        self.label_9.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(164, 182, 232, 0), stop:0.55 rgba(250, 104, 255, 0), stop:0.98 rgba(124, 205, 236, 0), stop:1 rgba(0, 0, 0, 0));")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Pics/liquid-gradient-shape-fluid-abstract-color-background-holographic-organic-3d-design-neon-futuristic-element-blend-bubble-png.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def data_sent_to_database(self):
        print("Data Sent Successfully")

        # retrieve data from line edit
        username=self.lineEdit_2.text()
        email=self.lineEdit_3.text()
        password=self.lineEdit_4.text()

        # if any field is empty show error
        if not username or not email or not password:
            print("Error: Please fill in all fields.")
            return
        final = "INSERT INTO SignupData (USERNAME,EMAIL,PASSWORD) VALUES('{}', '{}', '{}')".format(
            username, email, password)
        try:
# Write data in Database
            self.cursor = self.conn.cursor()
            self.cursor.execute(final)
            self.conn.commit()
            print("Data Sent to database successfully.")
        except pyodbc.Error as e:
            print("Please Fill All Fields Correctly")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "School Management System"))
        self.label.setText(_translate("MainWindow", "Create Account"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.label_5.setText(_translate("MainWindow", "UserName"))
        self.label_6.setText(_translate("MainWindow", "Email"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    MainWindow.setFixedHeight(532)
    MainWindow.setFixedWidth(425)
    sys.exit(app.exec_())
